name: octave
base: core18
version: '5.1.0'
summary: Interactive programming environment for numerical computations
description: |
  GNU Octave is a high-level interpreted language, primarily intended for
  numerical computations. It provides capabilities for the numerical
  solution of linear and nonlinear problems, and for performing other
  numerical experiments. It also provides extensive graphics capabilities
  for data visualization and manipulation. Octave is normally used through
  its interactive command line interface, but it can also be used to write
  non-interactive programs. The Octave language is quite similar to
  Matlab so that most programs are easily portable.

grade: stable
confinement: strict

apps:
  octave:
    command: bin/octave
    environment:
      LD_LIBRARY_PATH: "$SNAP/lib/octave/5.1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      OCTAVE_HOME: "$SNAP"
  octave-cli:
    command: bin/octave-cli
    environment:
      LD_LIBRARY_PATH: "$SNAP/lib/octave/5.1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      OCTAVE_HOME: "$SNAP"

parts:
  octave:
    plugin: autotools
    source-type: tar
    source: https://ftpmirror.gnu.org/octave/octave-5.1.0.tar.xz
    build-packages:
      - gfortran
      - libarpack2-dev
      - libcurl4-gnutls-dev
      - libfftw3-dev
      - libglpk-dev
      - libgraphicsmagick++1-dev
      - libhdf5-dev
      - libncurses5-dev
      - libopenblas-dev
      - libpcre3-dev
      - libqhull-dev
      - libqrupdate-dev
      - libreadline-dev
      - libsndfile1-dev
      - libsuitesparse-dev
      - portaudio19-dev
      - texinfo
    stage-packages:
      - libamd2
      - libarpack2
      - libcamd2
      - libccolamd2
      - libcholmod3
      - libcolamd2
      - libcurl3-gnutls
      - libcxsparse3
      - libfftw3-double3
      - libfftw3-single3
      - libglpk40
      - libgraphicsmagick++-q16-12
      - libhdf5-100
      - libopenblas-base
      - libpcre3
      - libportaudio2
      - libqhull7
      - libqrupdate1
      - libsndfile1
      - libumfpack5
      - texinfo
    organize:
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET/openblas: usr/lib/$SNAPCRAFT_ARCH_TRIPLET
